# TOML Lazy Plugin List

# 挿入モードで読み込むもの
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

# ファイル別で読み込むもの
# Python
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3', 'djangohtml']
[[plugins]]
repo = 'hdima/python-syntax'
on_ft = ['python', 'python3']
