# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# format = "$all"
format = """
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$aws$gcloud\
$jobs\
$cmd_duration\
$status\
$line_break\
$character
"""

add_newline = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
