# TOML Lazy Plugin List

# 特定のコマンドが呼ばれた時
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTree'

# ファイル別
# Python
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3', 'djangohtml']
#[[plugins]]
#repo = 'hdima/python-syntax'
#on_ft = ['python', 'python3']
