# TOML Lazy Plugin List

# ファイル操作
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

# 入力補助
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python', 'python3', 'htmldjango']
hook_add = '''
    let g:deoplete#sources#jedi#statement_length = 0
'''
[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = ['rust']
hook_add = '''
    let g:deoplete#sources#rust#racer_binary = '~/.cargo/bin/racer'
    let g:deoplete#sources#rust#rust_source_path = '~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src'
'''
