# TOML Plugin List

[[plugins]]
repo = 'Shougo/dein.vim'

# UI
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'


# File import utils
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# Color scheme
[[plugins]]
repo = 'joshdick/onedark.vim'

# python indent support
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# syntax highlight
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'rust-lang/rust.vim'
[[plugins]]
repo = 'lepture/vim-jinja'
[[plugins]]
repo = 'vim-ruby/vim-ruby'
