# TOML Lazy Plugin List

# ファイル操作
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTree'

# 入力補助
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python', 'python3', 'htmldjango']
hook_add = '''
    let g:deoplete#sources#jedi#statement_length = 0
'''
