# TOML Plugin List

[[plugins]]
repo = 'Shougo/dein.vim'

# UI
[[plugins]]
repo = 'itchyny/lightline.vim'

# File import utils
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# Color scheme
[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'
[[plugins]]
repo = 'sickill/vim-monokai'
[[plugins]]
repo = 'tomasr/molokai'

# python indent support
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# TOML syntax highlight
[[plugins]]
repo = 'cespare/vim-toml'
